name: Sous
options:
  bundleIdPrefix: com.lerebear
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
targets:
  Sous:
    type: application
    platform: iOS
    sources:
      - path: Sous
        excludes:
          - TestFixtures/**
      - path: Sous/TestFixtures
        type: folder
        buildPhase: resources
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.lerebear.Sous
        PRODUCT_NAME: Sous
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: Sous/Sous.entitlements
      properties: {}
  SousTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SousTests
    dependencies:
      - target: Sous
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.lerebear.SousTests
        PRODUCT_NAME: SousTests
  SousUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SousUITests
    dependencies:
      - target: Sous
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.lerebear.SousUITests
        PRODUCT_NAME: SousUITests
